name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
      
    - name: Minikube (Single node Kubernetes) Action
      # You may pin to the exact commit or the version.
      # uses: opsgang/ga-setup-minikube@1a073b7d3ef4976302b9a5e701128998b0a8e8c9
      uses: opsgang/ga-setup-minikube@v0.1.1
      #with:
        # Version of Minikube to use. Default: 1.4.0
        # minikube-version: # optional, default is 1.4.0
        # Version of Kubernetes to use. Default: 1.15.0
        # k8s-version: # optional, default is 1.15.0
 
    - name: Test
      run: go test -v ./...
