name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
      
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@9379083e426e2e84abb80c8c091f5cdeb7d3fd7a
      uses: docker/build-push-action@v2.3.0
      with:
        tags: 0x7369616c/go-hello-world:1.0.1
      
    - name: Setup Minikube Kubernetes Cluster
      # You may pin to the exact commit or the version.
      # uses: manusa/actions-setup-minikube@5118549e6b5b7a08d24c8f3d382d77a5c707746f
      uses: manusa/actions-setup-minikube@v2.3.0
      with:
        # Version of Minikube to deploy
        minikube version: v1.17.0
        # Version of Kubernetes to deploy
        kubernetes version: v1.20.0
        # GITHUB_TOKEN to be able to perform requests to GH REST API (with no limit)
        # github token: # optional
        # 
        # driver: # optional
          # 
        # start args: # optional
  
    - name: Test
      run: go test -v ./test/go_kubernetes_test.go
